config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'search' => 'search#index'
  get 'search/list' => 'search#list'
  get 'search/unlist' => 'search#unlist'
  get 'search/filter' => 'search#search'

  
  resources :listings

  get 'compare' => 'compare#index'

  

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :title, presence: true, length: {maximum: 255}
	validates :description, length: {maximum: 500}
	validates :price, presence: true
  validates :tour_code, presence: true
  validates :duration, presence: true
  validates :agency, presence: true
  validates :country, presence: true
  validates :city, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include CookieManager
  before_filter :cm_run
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def show
    @listing = Listing.find(params[:id])
  end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:search].nil?
      @search = Listing.all
      @search_params = ""
    else
      @search = Listing.where("title like ? OR description like ?", 
        "%"+params[:search]+"%", "%"+params[:search]+"%");
      @search_params = params[:search]
    end

    @shortlist = Listing.find(cm_shortlist)
    puts cm_shortlist.to_s
  end

  def search 
    price = params[:price].gsub('$','').split(' - ')

    @selected = Listing.where("(title like ? OR description like ?) AND (price > ? AND price < ?)", 
      "%"+params[:search]+"%", 
      "%"+params[:search]+"%",
      price.first,
      price.last );

    respond_to do |format|
      format.js
    end
  end

  def list
    if cm_shortlist_add params[:id]
      @compare = Listing.find(params[:id])
    else 
      @compare = nil
    end

    puts "Session: " + session[:current_user_shortlist].to_s

    respond_to do |format|
      format.js
    end
  end

  def unlist
    @remove = params[:id]

    cm_shortlist_remove params[:id]

    puts "Session: " + session[:current_user_shortlist].to_s

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "TravComList"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper

  def get_logo (agency)
    case agency
    when "Chan Brothers"
      "chanbrother_logo.png"
    when "New Shan"
      "newshan_logo.png"
    when "Dynasty Travel"
      "dynastytravel_logo.png"
    when "CTC Travel"
      "ctctravel_logo.png"
    when "ASA Holidays"
      "asaholidays_logo.png"
    else 
      nil
    end
  end

  def get_brochure_eng (agency, tour_code)
    case agency
    when "Chan Brothers"
      "chanbrother_" + tour_code + "_eng.pdf"
    when "New Shan"
      "newshan_" + tour_code + "_eng.pdf"
    when "Dynasty Travel"
      "dynastytravel_" + tour_code + "_eng.pdf"
    when "CTC Travel"
      "ctctravel_" + tour_code + "_eng.pdf"
    when "ASA Holidays"
      "asaholidays_" + tour_code + "_eng.pdf"
    else 
      nil
    end
  end

  def has_asset?(path)
    Rails.application.assets.find_asset(path) != nil
  end

end

app/helpers/search_helper.rb
module SearchHelper

  def get_logo (agency)
    case agency
    when "Chan Brothers"
      "chanbrother_logo.png"
    when "New Shan"
      "newshan_logo.png"
    when "Dynasty Travel"
      "dynastytravel_logo.png"
    when "CTC Travel"
      "ctctravel_logo.png"
    when "ASA Holidays"
      "asaholidays_logo.png"
    else 
      nil
    end
  end

end

app/views/home/_agency.html.erb
<div class="row">
  <div class="col s12">
    <h1 class="header"> Travel Agencies </h1>
  </div>
  <div class="container">
    <% for i in 1..9 do %>
      <div class="col s12 m6 l4">
        <div class="card waves-effect waves-block waves-light">
          <div class="card-image">
            <%= image_tag "room1.jpg", class:"activator" %>
            <span class="card-title">Agency <%= i %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_deal.html.erb
<div class="col s12">
  <h1 class="header"> Hot Deals </h1>
</div>
<div class="container">
  <% for j in 1..9 do %>
    <div class="col s12 m6 l4">
      <div class="card waves-effect waves-block waves-light">
        <div class="card-image">
          <%= image_tag "room1.jpg", class:"activator" %>
          <span class="card-title">Hot Deals <%= j %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_search.html.erb
<div class="jumbotron">
  <div class="video_container parallax-container">
    <div id="video" class="parallax"></div>
    <div class="video_case"></div>
    <div class="title">
      <h1> Find Your Perfect Trip </h1>
    </div>
    <div class="search_container">
      <div class="search">
        <div class="row">
          <h4 class="search_title"> Search for tour package now </h4>
          <form class="col s12" action="search">
            <div class="row">
              <div class="input-field col s12">
                <input placeholder="Where do you want to go?" id="search_location" type="text" class="validate" name="search">
                <label for="search_location">Location</label>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s6">
                <label for="start_date">Start Date (Disabled) </label>
                <input disabled type="date" class="datepicker" id="start_date">
              </div>
              <div class="input-field col s6">
                <label for="end_date">End Date (Disabled) </label>
                <input disabled type="date" class="datepicker" id="end_date">
              </div>
            </div>
            <button class="btn waves-effect waves-light right submit_button" type="submit" name="action">Submit
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- Search -->
<section id="search">
  <%= render 'search' %>
</section>
<!-- End of Search -->

<!-- Travel Agencies -->
<section id="agency">
  <%= render 'agency' %>
</section>

<div class="deals row">
  <%= render 'deal' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer theme">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright"> 
    <div class="container">
      <span> © 2014 Copyright Text </span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav class="theme">
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "Logo", root_path, class:'brand-logo' %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Search", search_path%></li>
          <li><a href="#">Link2</a></li>
          <li><a href="#">Link3</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application',params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application',params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navbar -->
<%= render 'layouts/header' %>


<!-- Body Partial -->
<%= yield %>

<!-- Footer -->
<%= render 'layouts/footer' %>
<%- debug(params) if Rails.env.development? -%> 
</body>
</html>

app/views/listings/_compare_advert.html.erb
<div class="deals">
  <%= image_tag("advert1.jpg", :class => "responsive-img") %>
</div>

app/views/listings/_filters.html.erb
<!-- Filters -->
<%= form_tag('/listings/search', :id => 'filter-form' ,:method => 'get', remote: true) do %> 
  <!-- Date Period -->
  <div class="col s12" id="filters">
    <div class="input-field col s6">
      <i class="material-icons prefix">today</i>
      <input type="date" name="start-date" class="datepicker">
      <label for="icon_prefix">Start Date</label>
    </div>

    <div class="input-field col s6">
      <i class="material-icons prefix">today</i>
      <input type="date" name="end-date" class="datepicker">
      <label for="icon_prefix">End Date</label>
    </div>
    <!-- End of Date Period -->

    <!-- Price Range -->
    <div class="col s12">
      <p class="range-field">
        <i class="material-icons prefix">today</i>
        <label for="icon_prefix">Price Range</label>
        <!-- <input type="range" id="test5" min="0" max="100" /> -->
        <input type="text" id="amount" name="price" readonly style="border:0; color:#f6931f; font-weight:bold;">
        <div id="slider-range"></div>
      </p>
    </div>
    <!-- End of Price Range -->
    
    <!-- Search -->
    <div class="input-field col s12">
      <input id="search" type="search" name="search">
      <label for="search"><i class="material-icons">search</i> What is your destination?</label>
    </div>
    <!-- End of Search -->
  </div>
<% end %>
<!-- End of Filters -->

app/views/listings/_listing.html.erb
<div class="listing-overlay">
  <div class="content row">
    <span class="close clickable"><i class="fa fa-times"></i></span>
    <div class="card medium">
      <div class="card-image">
        <%= image_tag("room1.jpg") %>
      </div>
      <div class="card-content">
        <h5 class="title">
          <span class="text"></span>
        </h5>
        <div class="col s6">
          <p class="dura">
            Duration: <strong><span class="text"></span></strong>
          </p>
        </div>
        <div class="col s6">
          <p class="price">
            Price: <strong><span class="text"></span></strong>
          </p>
        </div>
        <p class="desc">
          <span class="text"></span>
        </p>
      </div>
      <div class="card-action">
        <a href="#" class="compare" data-link="">Compare</a>
        <a href="#" class="more-info">More Info</a>
      </div>
    </div>
  </div>
</div>

app/views/listings/_listing_items.html.erb
<div class="col s12 m6">
  <div class="listing card medium hoverable">
    <div class="clickable">
      <div class="card-image">
        <%= image_tag("room1.jpg") %>
        <span class="card-day"> <%= list.title.split(" ").first %> </span>
        <span class="card-price"> $<%= list.price %></span>
      </div>
      <div class="card-content">
        <p class="card-title">
          <%= list.title %>
        </p>
        <p class="card-description truncate">
          <%= list.description %>
        </p>
      </div>
    </div>
    <div class="card-action">
      <a href="#" class="compare" data-link="<%= list.id %>">Compare</a>
      <%= link_to "More Info", list, class: "more-info" %>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<% provide(:title, " Listings") %>

<!-- Contents -->
<div class="listing-page">
  <div class="row">
    <div class="col s12 l9 fixed sidebar-left">
      <%= render 'listings/filters' %>
      <div id="listings-grid">
        <%= render partial: 'listing_items', collection: @listings_all, as: :list %>
      </div>
    </div> <!-- End of Col -->
    <div class="col l3 sidebar-right fixed">
      <div class="shortlist">
        <a href="#"><h5 class="header">Compare <i class="fa fa-chevron-right"></i></h5></a>
        <div class="divider"></div>
        <ul class="collection" id="compare-list">
          <% if @compare.nil? %>
            <li class="empty"> There is nothing here :( </li>
          <% else %>
            <%= render partial: 'compare', collection: @compare, as: :list %>
          <% end %>
        </ul>
        <%- render 'listings/compare_advert' -%>
      </div>
      <div class="handle clickable">
        <i class="fa fa-angle-double-left"></i>
      </div>
    </div> <!-- End of Col -->
  </div> <!-- End of Row -->
</div> <!-- End of Listing Page -->

<%= render 'listings/listing' %>

app/views/listings/show.html.erb
<% provide(:title, @listing.title) %>

<div class="showcase" style="background-image:url('<%= image_url "room1.jpg" %>')">
</div>

<div class="container">
  <div class="row">
    <div class="col s12">
      <h4> <%= @listing.title %> </h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col offset-s4 s8 offset-m8 m4" style="vertical-align: bottom">
      <ul class="tabs">
        <li class="tab col s4"><a href="#info">Info</a></li>
        <li class="tab col s4"><a href="#iti">Iti</a></li>
        <li class="tab col s4"><a href="#pdf">PDF</a></li>
      </ul>
    </div>
    <div id="info" class="col s12 tab-content">
      <div class="col s12">
        <div class="col s8">
          <p> 
            <label>Tour type:</label> 
            <%= @listing.listing_type %> 
          </p>
          <p> 
            <label>Tour code:</label> 
            <%= @listing.tour_code %> 
          </p>
          <p> 
            <label>Price from:</label> 
            <% if @listing.price != 0 %>
              $<%= @listing.price %> 
            <% else %>
              Enquire to know more
            <% end %>
          </p>
          <p> 
            <label>Availability till:</label> 
            <% if !@listing.expiration_date.blank? %>
              <%= @listing.expiration_date %> 
            <% else %>
              Enquire to know more
            <% end %>
          </p>
          
          <p> 
            <a href="<%= @listing.origin_link %>"> Click here for <%= @listing.agency %> page</a>
          </p>
        </div>

        <div class="col s4">
          <p class="center-align"> Brought to you by: </p>
          <% $logo = get_logo(@listing.agency) %>
          <p class="center-align"> <%= image_tag($logo, class:"logo") %> </p>
        </div>
      </div>

      <div class="col s12">
        <% if !@listing.description.blank? %>
          <div class="col s12 border-top">
            <p class="center-align"> 
              <label>Descripion:</label>
            </p>
            <p>
              <%= @listing.description %>
            </p>
          </div>
        <% end %>

        <% if !@listing.places_of_interest.to_a.empty? %>
          <div class="col s12 border-top">
            <p class="center-align">
              <label> Highlights: </label>
            </p>
            <% @listing.places_of_interest.each do |place| %>
              <div class="col s6 m4">
                <p> • <%= place %> </p>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>

    <div id="iti" class="col s12 tab-content">
      <% if !@listing.itinenary.to_a.empty? %>
        <table class="striped">
          <tbody>
            <% $i = 1 %>
            <% @listing.itinenary.each do |key, data| %>
              <tr>
                <td>
                  <span class="day"> Day <%= $i %> </span>
                  <% data.each do |item, val| %>
                    <label> <%= item %> </label>
                    <p> <%= val %> </p>
                  <% end %>
                </td>
              </tr>
              <% $i+= 1 %>
            <% end %>
          </tbody>
        </table>  
      <% end %>
    </div>

    <div id="pdf" class="col s12 tab-content">
      <% $brochure = get_brochure_eng(@listing.agency, @listing.tour_code) %>
      <% if has_asset?($brochure) %>
        <embed src="<%= asset_path($brochure) %>" width="100%" height="800px" type="application/pdf">
      <% else %>
        <h6 class="center-align"> There is no pdf file. </h6>
      <% end %>
    </div>
    
  </div>
</div>

app/views/listings/uncompare.js.erb
$( "#compare-list" ).find( 'li[data-link="<%= @remove %>"]' ).remove();

if ($( "#compare-list" ).has( "li" ).length <= 0) {
	$( "#compare-list" ).append("<li class='empty'> There is nothing here :( </li>");
}

app/views/search/_advert.html.erb
<div class="deals">
  <%= image_tag("advert1.jpg", :class => "responsive-img") %>
</div>

app/views/search/_filters.html.erb
<!-- Filters -->
<%= form_tag('/search/filter', :id => 'filter-form' ,:method => 'get', remote: true) do %> 
  <!-- Date Period -->
  <div class="col s12" id="filters">
    <div class="input-field col s6">
      <i class="material-icons prefix">today</i>
      <input disabled type="date" name="start-date" class="datepicker">
      <label for="icon_prefix">Start Date (Disabled) </label>
    </div>

    <div class="input-field col s6">
      <i class="material-icons prefix">today</i>
      <input disabled type="date" name="end-date" class="datepicker">
      <label for="icon_prefix">End Date (Disabled) </label>
    </div>
    <!-- End of Date Period -->

    <!-- Price Range -->
    <div class="col s12">
      <p class="range-field">
        <i class="material-icons prefix">today</i>
        <label for="icon_prefix">Price Range</label>
        <!-- <input type="range" id="test5" min="0" max="100" /> -->
        <input type="text" id="amount" name="price" readonly style="border:0; color:#f6931f; font-weight:bold;">
        <div id="slider-range"></div>
      </p>
    </div>
    <!-- End of Price Range -->
    
    <!-- Search -->
    <div class="input-field col s12">
      <input id="search" type="search" name="search" value="<%= @search_params %>">
      <label for="search"><i class="material-icons">search</i> What is your destination?</label>
    </div>
    <!-- End of Search -->
  </div>
<% end %>
<!-- End of Filters -->

app/views/search/_overlay.html.erb
<div class="listing-overlay">
  <div class="content row">
    <span class="close clickable"><i class="fa fa-times"></i></span>
    <div class="card medium">
      <div class="card-image">
        <%= image_tag("room1.jpg") %>
      </div>
      <div class="card-content">
        <h5 class="title">
          <span class="text"></span>
        </h5>
        <div class="col s6">
          <p class="dura">
            Duration: <strong><span class="text"></span></strong>
          </p>
        </div>
        <div class="col s6">
          <p class="price">
            Price: <strong><span class="text"></span></strong>
          </p>
        </div>
        <p class="desc">
          <span class="text"></span>
        </p>
      </div>
      <div class="card-action">
        <a href="#" class="compare" data-link="">Compare</a>
        <a href="#" class="more-info">More Info</a>
      </div>
    </div>
  </div>
</div>

app/views/search/_search_result.html.erb
<div class="col s12 m6">
  <div class="listing card medium hoverable">
    <div class="clickable">
      <div class="card-image">
        <%= image_tag("room1.jpg") %>
        <span class="card-day"> <%= list.duration %> Days </span>
        <span class="card-price"> fr. $<%= list.price %></span>
      </div>
      <div class="card-content">
        <p class="card-title"> <%= list.title %> </p>
        <p class="card-description truncate"> <%= list.description %> </p>
      </div>
    </div>
    <div class="card-action">
      <a href="#" class="compare" data-link="<%= list.id %>">Compare</a>
      <%= link_to "More Info", list, class: "more-info" %>
    </div>
  </div>
</div>

app/views/search/_shortlist.html.erb
<li class="collection-item dismissable" data-link="<%= list.id %>">
  <div class="list">
    <div class="col s12">  
      <p class="agency"> <%= list.agency %> </p>   
    </div>
    <div class="col s12">   
      <p class="truncate title"><%= list.title %></p> 
    </div>
    <div class="col s6">
      <p class="day"><%= list.duration %> Days</p>
    </div>
    <div class="col s6">
      <p class="price">from $<%= list.price %></p>
    </div>
    <div class="col s12">    
      <p class="truncate description"><%= list.description %></p>
    </div>
    <span href="#!" class="secondary-content remove"><i class="fa fa-times"></i></span>
  </div>
</li>

app/views/search/index.html.erb
<% provide(:title, "Search") %>

<!-- Contents -->
<div class="listing-page">
  <div class="row">
    <div class="col s12 l9 fixed sidebar-left">
      <%= render partial: 'search/filters' %>
      <div id="listings-grid">
        <%= render partial: 'search_result', collection: @search, as: :list %>
      </div>
    </div> <!-- End of Col -->
    <div class="col l3 sidebar-right fixed">
      <div class="shortlist">
        <a href="compare"><h5 class="header">Compare <i class="fa fa-chevron-right"></i></h5></a>
        <div class="divider"></div>
        <ul class="collection" id="compare-list">
          <% if @shortlist.blank? %>
            <li class="empty"> There is nothing here :( </li>
          <% else %>
            <%= render partial: 'shortlist', collection: @shortlist, as: :list %>
          <% end %>
        </ul>
        <%- render partial: 'search/advert' -%>
      </div>
      <div class="handle clickable">
        <i class="fa fa-angle-double-left"></i>
      </div>
    </div> <!-- End of Col -->
  </div> <!-- End of Row -->
</div> <!-- End of Listing Page -->

<%= render partial: 'overlay' %>

app/views/search/list.js.erb
<% if @compare.nil? %>

<% else %>
  $( "#compare-list .empty" ).remove();
  $( "#compare-list" ).append( "<%= escape_javascript(render partial: 'shortlist', 
    locals:{list: @compare}) %>" );

  $( ".remove" ).click(function() {
    $.get('search/unlist', {id: $( this ).closest(" li.dismissable ").attr("data-link")});
  });

  Materialize.toast("Added <%= @compare.title %>", 2000);
<% end %>

app/views/search/search.js.erb
$("#listings-grid").html("<%= escape_javascript(render partial: 'search_result', 
	collection: @selected, as: :list) %>");

app/views/search/unlist.js.erb
var component = $( "#compare-list" ).find( 'li[data-link="<%= @remove %>"]' );
var title = component.find('.title').html();

component.remove();

if ($( "#compare-list" ).has( "li" ).length <= 0) {
	$( "#compare-list" ).append("<li class='empty'> There is nothing here :( </li>");
}

if (title != undefined) {
  Materialize.toast("Removed " + title, 2000);
} 